import { ThemeColor } from '../types';

export const THEME_COLORS: ThemeColor[] = [
  { name: 'Indigo', primary: '#4f46e5', light: '#eef2ff', dark: '#3730a3' },
  { name: 'Royal Blue', primary: '#2563eb', light: '#eff6ff', dark: '#1e40af' },
  { name: 'Navy', primary: '#1e3a5f', light: '#e0f2fe', dark: '#0c2340' },
  { name: 'Crimson', primary: '#dc2626', light: '#fef2f2', dark: '#991b1b' },
  { name: 'Emerald', primary: '#059669', light: '#ecfdf5', dark: '#065f46' },
  { name: 'Teal', primary: '#0d9488', light: '#f0fdfa', dark: '#115e59' },
  { name: 'Purple', primary: '#7c3aed', light: '#f5f3ff', dark: '#5b21b6' },
  { name: 'Violet', primary: '#6d28d9', light: '#ede9fe', dark: '#4c1d95' },
  { name: 'Orange', primary: '#ea580c', light: '#fff7ed', dark: '#9a3412' },
  { name: 'Amber', primary: '#d97706', light: '#fffbeb', dark: '#92400e' },
  { name: 'Rose', primary: '#e11d48', light: '#fff1f2', dark: '#9f1239' },
  { name: 'Pink', primary: '#db2777', light: '#fdf2f8', dark: '#9d174d' },
  { name: 'Cyan', primary: '#0891b2', light: '#ecfeff', dark: '#155e75' },
  { name: 'Sky', primary: '#0284c7', light: '#f0f9ff', dark: '#075985' },
  { name: 'Slate', primary: '#475569', light: '#f8fafc', dark: '#1e293b' },
  { name: 'Gray', primary: '#374151', light: '#f9fafb', dark: '#111827' },
  { name: 'Lime', primary: '#65a30d', light: '#f7fee7', dark: '#3f6212' },
  { name: 'Fuchsia', primary: '#c026d3', light: '#fdf4ff', dark: '#86198f' },
  { name: 'Maroon', primary: '#991b1b', light: '#fef2f2', dark: '#7f1d1d' },
  { name: 'Forest', primary: '#134e4a', light: '#f0fdfa', dark: '#042f2e' },
];

export const TEMPLATE_INFO: { name: string; category: string; description: string }[] = [
  { name: 'Modern Accent', category: 'Professional', description: 'Indigo titles, dual sectioning, great for tech.' },
  { name: 'Professional Executive', category: 'Traditional', description: 'Serif fonts, center alignment, corporate styling.' },
  { name: 'Creative Dynamic', category: 'Creative', description: 'Bold colored sidebar layout for designers.' },
  { name: 'Minimal Clean', category: 'Simple', description: 'Highly readable geometry with whitespace.' },
  { name: 'Premium Sidebar', category: 'Professional', description: 'Dark sidebar with main content focus.' },
  { name: 'Tech Terminal', category: 'Tech', description: 'Developer-focused with code aesthetic.' },
  { name: 'Elegant Gradient', category: 'Modern', description: 'Soft gradients with modern typography.' },
  { name: 'Bold Header', category: 'Professional', description: 'Strong centered title with accents.' },
  { name: 'Timeline Pro', category: 'Professional', description: 'Timeline-based experience section.' },
  { name: 'Grid Modern', category: 'Modern', description: 'Card-based sections with grid layout.' },
  { name: 'Vintage Classic', category: 'Creative', description: 'Warm vintage-inspired design.' },
  { name: 'Sleek Dark', category: 'Modern', description: 'Dark themed professional resume.' },
  { name: 'Clean Lines', category: 'Simple', description: 'Sharp lines with minimal decoration.' },
  { name: 'Color Block', category: 'Creative', description: 'Bold color blocks for sections.' },
  { name: 'Corporate Blue', category: 'Traditional', description: 'Classic corporate blue theme.' },
  { name: 'Modern Compact', category: 'Modern', description: 'Dense layout for experienced pros.' },
  { name: 'Artistic Flair', category: 'Creative', description: 'Creative industry focused design.' },
  { name: 'Swiss Design', category: 'Modern', description: 'Swiss typographic precision.' },
  { name: 'Futuristic', category: 'Modern', description: 'Modern geometric shapes.' },
  { name: 'Eco Nature', category: 'Creative', description: 'Nature-inspired green palette.' },
  { name: 'Voice Pro', category: 'Premium', description: 'Photo sidebar with banner header sections.' },
  { name: 'Academic Split', category: 'Traditional', description: 'Two-column with vertical divider for academics.' },
  { name: 'Boxed Modern', category: 'Modern', description: 'Gray boxed sections with photo header.' },
  { name: 'Engineer Blue', category: 'Professional', description: 'Navy sidebar with centered banner name.' },
];
